### PR TITLE
Rename to sensuclassic

### PR DESCRIPTION
**Pull request by treydock**
# Pull Request Checklist

## Description

Rename all resources from `sensu` to `sensuclassic`.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
- [ ] metadata.json - name is `sensu-sensuclassic` - other values need updates, too
- [ ] sensu -> sensuclassic in names under `acceptances/nodesets`
- [ ] README.md
- [ ] CONTRIBUTING.md

**Comment by treydock** [comment]
Pushed several commits to address outstanding issues.  Ran local acceptance and things are looking good , just waiting for travis to run the tests.

**Comment by ghoneycutt** [comment]
Looks good. I'm testing everything in Vagrant now.

**Comment by ghoneycutt** [comment]
@treydock 

`el6-client: Error: Parameter provider failed on Package[sensu-plugin]: Invalid package provider 'sensu_gem' (file: /etc/puppetlabs/code/environments/production/modules/sensuclassic/manifests/package.pp, line: 205)`

Since sensu-go does not have the `sensu_gem` provider, perhaps we can just use `sensu_gem` instead of `sensuclassic_gem`?

**Comment by ghoneycutt** [comment]
**Vagrant**

- [x] sensu-server
- [x] sensu-server-cluster
- [x] sensu-server-puppet6
- [x] sensu-server-enterprise
- [x] el7-client
- [x] el6-client - sensu_gem
- [x] ubuntu1804-client
- [x] ubuntu1604-client
- [x] ubuntu1404-client - sensu_gem
- [x] win2012r2-client - issue noted
- [x] debian9-client
- [x] debian8-client
- [x] macos-client

**Comment by treydock** [comment]
I opted to rename the provider in the unlikely event we may need custom package providers with sensu-go.  We could in theory use something like `sensu_gem` with the new plugins/extensions for sensu-go but I opted to use `sensu-install` command.  If we ended up needing custom provider I was concerned there'd be a conflict.

**Comment by ghoneycutt** [comment]
`ubuntu1404-client: Error: Parameter provider failed on Package[sensu-plugin]: Invalid package provider 'sensu_gem' (file: /etc/puppetlabs/code/environments/production/modules/sensuclassic/manifests/package.pp, line: 205)`

**Comment by treydock** [comment]
Added 2 commits that should resolve those issues.

**Comment by ghoneycutt** [comment]
```
Bringing machine 'win2012r2-client' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.
```

**Comment by ghoneycutt** [comment]
I've got commits to fix..hold on a sec before committing more

**Comment by ghoneycutt** [comment]
Could you merge https://github.com/treydock/puppet-module-sensuclassic/pull/1 

Those are all my fixes for vagrant

**Comment by treydock** [comment]
That reload error is missing vagrant plugin, something we had to add to support installing powershell 5 and rebooting VM to apply the change.  It's necessary to support DSC resources.

**Comment by treydock** [comment]
Merged PR on fork

**Comment by ghoneycutt** [comment]
Fix for reload issue associated with windows box - https://github.com/treydock/puppet-module-sensuclassic/pull/2

**Comment by ghoneycutt** [comment]
```
==> win2012r2-client: Machine booted and ready!
==> win2012r2-client: Configuring proxy environment variables...
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir "/" -force

Stdout from the command:



Stderr from the command:

The path is not of a legal form.
At line:1 char:1
+ mkdir "/" -force
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\:String) [New-Item], ArgumentException
    + FullyQualifiedErrorId : CreateDirectoryArgumentError,Microsoft.PowerShell.Commands.NewItemCommand
```

**Comment by ghoneycutt** [comment]
el6 and ubuntu14 - both having issues with sensu_gem. They now provision correctly, though I don't see them registered in Uchiwa. You can check against the API with

```bash
function sensuclients {
  curl -s http://admin:secret@127.0.0.1:4567/clients | jq .[].name | awk -F \" '{print $2}' | awk -F \. '{print $1}' | sort
}
```

**Comment by treydock** [comment]
Not sure where that mkdir is coming from, not seeing `mkdir` in `tests` directory.

**Comment by ghoneycutt** [comment]
proxy plugin perhaps?

**Comment by ghoneycutt** [comment]
EL6 and Ubuntu 14.04 fixed with https://github.com/treydock/puppet-module-sensuclassic/pull/3

**Comment by treydock** [comment]
Merged

**Comment by treydock** [comment]
Ran `win2012r2-client` locally and it was successful.  Only plugins I have installed are reload, share and vbguest.

**Comment by treydock** [comment]
Marking off sensu-server-cluster, sensu-server-puppet6 and sensu-server-enterprise.  Ran them all locally and they worked.  Also updated all boxes to query correct fact at the end of provision.

**Comment by ghoneycutt** [comment]
Rebased and Squashed in PR #6

**Pull request closed without merging**
